version: 0.2

phases:
  install: 
    runtime-versions:
      java: latest
    commands:
      - apt update -y
      - apt install -y maven
      - apt install -y openjdk-17-jdk
      - apt install zip -y
  build:
    commands:
      - mvn clean install
artifacts:
  files:
    - target/webapp-1-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - beforeinstall.sh
    - applicationstart.sh
  discard-paths: yes
